# Generated by Django 3.2.13 on 2022-06-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.ImageField(default=1, upload_to='album'),
            preserve_default=False,
        ),
    ]
