# Generated by Django 3.2.13 on 2022-05-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_name_team_activities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='activities',
            new_name='name',
        ),
    ]
